### ISSUE TITLE
Why do no do

### ISSUE THREAD

**Issue by alex-arhat** [rainphp/raintpl#17]
Hierarchy:

<pre>
tpl_dir/
--blocks
----header.html
----footer.html
--admin
----pageeditor.html
index.html
</pre>

I'm want  include header block from admin/pageeditor

<pre>
{include="../blocks/header"}
</pre>

<b>Fatal error</b>:  Uncaught exception 'RainTpl_NotFoundException' with message 'Template header not found!' in /opt/lampp/htdocs/Library/RainTPL/rain.tpl.class.php:260
Stack trace:
#0 /opt/lampp/htdocs/Library/RainTPL/rain.tpl.class.php(154): RainTPL-&gt;check_template('/../blocks/head...')
#1 /opt/lampp/htdocs/Templates/cache/pageeditor.eed1c5179923c7c326c9cbd3ed186e30.php(3): RainTPL-&gt;draw('/../blocks/head...')
#2 /opt/lampp/htdocs/Library/RainTPL/rain.tpl.class.php(165): include('/opt/lampp/htdo...')

...

but from index fine work:

<pre>
{include="blocks/header"}
</pre>

Why?

**Comment by manguto** [comment]
Hi, I reached the same issue, and found at the reducePath() method, a infinity loop triyng to clear all "../" strings, but it wont work, so loops forever. 
I commented lines below, and it seems to be working now.   

_while( preg_match( '#\.\./#', $path ) ){
 $path = preg_replace('#\w+/\.\./#', '', $path );
}_

I'm using Rain Tpl 3.

**Comment by feulf** [comment]
Hi, I'm not supporting this project any more, please go ahead and do a
fork, thanks!
