### ISSUE TITLE
Translation/language with RainTPL?

### ISSUE THREAD

**Issue by xPaw** [rainphp/raintpl#20]
I saw on forum you promised to add **{@string@}** tag, could you please add to next version?

**Comment by bozhinov** [comment]
Hello,

What I did is created an anonymous function to translate the string and then assigned that  to a variable and called it inside tpl

`
$translate = function($word)
{
	global $locale;
	return $locale->translate($word);
};

$tpl = new Tpl();
$tpl->assign("translate", $translate);
`

then in the template:
`
<span class="mtxt">{$value.name|$translate}</span></a>
`
