### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by mirabilos** [rainphp/raintpl#57]
Hi,

we’re going to package this for Debian as part of the [effort to package Movim](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858367), and it would tremendously help us if you could please tag a formal release within the next… 72 hours or so, if possible early (we’re currently having a hacking session).

Thanks in advance!

**Comment by edhelas** [comment]
Actually I was able to use the v3.1.0 release from raintpl3 https://github.com/feulf/raintpl3/releases/tag/3.1.0 so this ticket can be closed :)

**Comment by mirabilos** [comment]
I see that raintpl3 is completely separate from raintpl and installs into separate paths, so I can just package it as a separate Debian package. Then please disregard this issue, closing.

**Comment by feulf** [comment]
Awesome
